//package rules.refuse
import com.shadeien.drools.Refuse

global java.util.HashMap refuseDate
global java.lang.Integer maxAge
global java.lang.Integer minAge
global java.util.Arrays$ArrayList list

rule "你好嘛"
	no-loop true
	lock-on-active true
	salience 0
	when
	    $data:Integer($data>minAge) from list
	then
		System.out.println("baseMessage0==="+$data);
		refuseDate.put("baseMessage0","0");
end

rule "baseMessage"
	no-loop true
	lock-on-active true
	salience 0
	when
		$re:Refuse(age>=maxAge||age<minAge)
	then
		System.out.println("baseMessage==="+$re);
		refuseDate.put("baseMessage","0");
end


rule "baseMessage2"
	no-loop true
	lock-on-active true
	salience 2
	when
		$re:Refuse(age>=60||age<22)
	then
		System.out.println("baseMessage2==="+$re);
		refuseDate.put("baseMessage2","ggggg");
end

rule "baseMessage1"
	no-loop true
	lock-on-active true
	salience 1
	when
		$re:Refuse(age<60&&age>=22)
	then
		System.out.println("baseMessage1==="+$re);
		refuseDate.put("baseMessage1","0");
end