spring:
  profiles:
    active: dev
  application:
    name: apollo
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  jmx:
    default-domain: ${spring.profiles.active}-apollo

eureka:
  client:
    service-url:
      defaultZone: http://172.16.4.176:8080/eureka/

apollo:
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application,business,bxz.common
  meta: http://172.16.4.176:8080


app:
  id: bxz-warehouse

server:
  port: 8082
